baseURL = 'https://ai.mattermost.com'
url = 'https://ai.mattermost.com'
languageCode = 'en-us'
title = 'Mattermost AI Framework'
canonifyURLs = true
theme = 'ananke'
[params]
  Header_classes = 'baba'
  body_classes = "avenir light-gray bg-transparent"
  post_content_classes = "avenir light-gray bg-transparent"
  background_color_class = 'bg-transparent'
  custom_css = ["styles.css"]
  favicon = "images/favicon.png"

[menu]
[[params.menuItems]]
  name = 'mattermost-ai-framework'
  url = 'https://github.com/mattermost/mattermost-ai-framework'
  weight = 1
  targetBlank = true
[[params.menuItems]]
  name = 'mattermost-plugin-ai'
  url = 'https://github.com/mattermost/mattermost-plugin-ai'
  weight = 2
  targetBlank = true
[[params.menuItems]]
  name = 'Docs'
  url = 'https://docs.mattermost.com/about/mattermost-customizable-ai-bot-framework.html'
  weight = 3
  targetBlank = true
[[params.menuItems]]
  name = 'Get Involved'
  url = '/get-involved'
  weight = 5
  targetBlank = false

