baseURL = 'https://ai.mattermost.com'
url = 'https://ai.mattermost.com'
languageCode = 'en-us'
title = 'Mattermost AI Framework'
canonifyURLs = true
theme = 'ananke'
[params]
  body_classes = "avenir light-gray bg-transparent"
  post_content_classes = "avenir light-gray bg-transparent"
  background_color_class = 'bg-transparent'
  custom_css = ["styles.css"]
