baseURL = 'https://mattermost.github.io/mattermost-ai-site/'
languageCode = 'en-us'
title = 'Mattermost AI Framework'
theme = 'ananke'
[params]
  body_classes = "avenir light-gray bg-transparent"
  post_content_classes = "avenir light-gray bg-transparent"
  background_color_class = 'bg-transparent'
  custom_css = ["styles.css"]
